#!/usr/bin/env bash
#
# Usage: ./backup-random
#
# A quick-and-dirty script that copies an archive of some sensitive
# directories and places them inside of a mounted virtual disk that's
# backed by an encrypted sparse disk image.

set -e

# Mount point for an encrypted sparse disk image
BACKUP_DEST=/Volumes/Secure\ Documents/Backups

if [ ! -d "$BACKUP_DEST" ]; then
  echo "Please mount your Secure Documents disk"
  exit 1
fi

TMP_FOLDER=/tmp/aps-backup-$(uuidgen)
mkdir $TMP_FOLDER

tar -zcvf "$TMP_FOLDER/ssh.tar.gz" -C ~/.ssh .
tar -zcvf "$TMP_FOLDER/aws.tar.gz" -C ~/.aws .
tar -zcvf "$TMP_FOLDER/keychain.tar.gz" -C ~/Library/Keychains .

cp -r $TMP_FOLDER "$BACKUP_DEST/$(date "+%Y-%m-%d_%H-%M-%S")"

rm -rf $TMP_FOLDER
